services:
  postgres:
    image: postgres:16-alpine
    container_name: finwise-db
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: finwise
      POSTGRES_PASSWORD: finwise
      POSTGRES_DB: finwise
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
